### PR TITLE
Done the displaying of high score

### PR DESCRIPTION
**Pull request by bryanojh**
changed Building acronyms to align with assg doc, changed starting coins to 16 instead of 1.

### CODE REVIEW

**Review by warrenkenzie — CHANGES_REQUESTED** [review]
Enable to code to read a text file and display the top 10 players. You can make some sample data for now in the text file.

**Comment by bryanojh** [comment]
Changes requested have been made, please review and check, thank you!

**Review by warrenkenzie — APPROVED** [review]
Looks good. I can see an improvement where you can store the txt file inside the project

**Comment by bryanojh** [comment]
Changed filepath for topscorers text file to project filepath

**Pull request merged**
